parameters:
  - name: projectname
    type: string
    default: 'devsu-demo-devops-python'
    displayName: 'Nombre del proyecto/repo'
  - name: imageRepository
    type: string
    default: 'ronnyt854/demo-devops-python'
    displayName: 'Nombre del repositorio de imagen Docker'
  - name: dockerfilePath
    type: string
    default: 'devsu-demo-devops-python/Dockerfile'
    displayName: 'Ruta del Dockerfile'
  
  # ==========================================
  # PARÁMETROS SONARCLOUD
  # ==========================================
  - name: runSonarAnalysis
    type: boolean
    default: false
    displayName: 'Ejecutar análisis de SonarCloud'
  - name: sonarProjectName
    type: string
    default: 'prueba-tecnica-devsu-ronny-tabango'
    displayName: 'Nombre del proyecto en SonarCloud'
  - name: sonarOrganization
    type: string
    default: 'ronny854'
    displayName: 'SonarCloud Organization (ej: tu-org-sonarcloud)'

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - devsu-demo-devops-python/**

stages:
- template: stages/buildPythonStage.yml
  parameters:
    projectname: '${{ parameters.projectname }}'
    imageRepository: '${{ parameters.imageRepository }}'
    tag: '$(Build.BuildId)'
    dockerfilePath: '${{ parameters.dockerfilePath }}'
    runSonarAnalysis: ${{ parameters.runSonarAnalysis }}
    sonarProjectName: '${{ parameters.sonarProjectName }}'
    sonarOrganization: '${{ parameters.sonarOrganization }}'

- template: stages/kubernetesDeploy.yml