# Stage para validar acceso a minikube y Docker
stages:
- stage: ValidateMinikubeAndDocker
  displayName: "Validar acceso a Minikube y Docker"
  dependsOn: [build]
  jobs:
  - job: CheckMinikubeAndDocker
    displayName: "Verificar kubectl y docker"
    pool:
      name: minikube-agents
    steps:
      - checkout: templates
      - task: DownloadSecureFile@1
        displayName: 'Donwload ssh key for minikube access'
        name: sshKey
        inputs:
          secureFile: 'azure-agent-key'
      - script: |
          echo "== Preparando SSH =="
          chmod 600 $(sshKey.secureFilePath)
          echo "Verificando pods en todos en el servidor Minikube:"
          ssh -o StrictHostKeyChecking=no -i $(sshKey.secureFilePath) ronny@10.0.2.3 "kubectl -- get pods -A"
          echo "\nVerificando contenedores Docker:"
          ssh -o StrictHostKeyChecking=no -i $(sshKey.secureFilePath) ronny@10.0.2.3 "docker ps"
        displayName: "kubectl get pods y docker ps"
