apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: myapp
  labels:
    app: demo-devops-python
    component: backend
data:
  APP_ENV: "production"
  DEBUG: "False"
  DATABASE_NAME: "data/db.sqlite3"
  ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,demo-devops-python.local,demo-devops-python-service"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"