apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-python
  namespace: myapp
  labels:
    app: demo-devops-python
    component: backend
    version: v1
  annotations:
    description: "Backend principal de la app DevOps Python"
    maintainer: "DevOps Team"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-devops-python
  template:
    metadata:
      labels:
        app: demo-devops-python
    spec:
      containers:
        - name: demo-devops-python
          image: docker.io/ronnyt854/demo-devops-python:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
