apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-python
  namespace: myapp
  labels:
    app: demo-devops-python
    component: backend
spec:
  rules:
    - host: demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-devops-python
                port:
                  number: 80