apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-sqlite-pvc
  namespace: myapp
  labels:
    app: demo-devops-python
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi