apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: myapp
  labels:
    app: demo-devops-python
    component: secret
type: Opaque
stringData:
  # IMPORTANTE: En producción real, este valor debe ser generado de forma segura
  # y gestionado mediante Azure Key Vault o un gestor de secretos
  DJANGO_SECRET_KEY: "django-insecure-wc2i2*6^17$9!u+(u66@q_rg)++n1x-^(0-$3yz2f(n=_-o*7="
  
  # Si en el futuro necesitas credenciales de BD externa:
  # DB_PASSWORD: "your-secure-password"
  # DB_HOST: "postgres.default.svc.cluster.local"
  # DB_PORT: "5432"
  # DB_NAME: "demo_devops"
  # DB_USER: "postgres"