apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: myapp
  labels:
    app: demo-devops-python
    component: backend
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXdjMmkyKjZeMTckOSF1Kyh1NjZAcV9yZykrK24xeC0oKDAtJDN5ejJmKG49Xy1vKjctPQ==