apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: myapp
  labels:
    app: demo-devops-python
    component: secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "DJANGO_SECRET_KEY_PLACEHOLDER"
  