apiVersion: v1
kind: Service
metadata:
  name: demo-devops-python
  namespace: myapp
  labels:
    app: demo-devops-python
    component: backend
  annotations:
    description: "Service para exponer la aplicación demo-devops-python"
spec:
  selector:
    app: demo-devops-python
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP