apiVersion: v1
kind: Service
metadata:
  name: demo-devops-python-service
  namespace: myapp
  labels:
    app: demo-devops-python
    component: backend
  annotations:
    description: "Service para exponer la aplicación demo-devops-python"
spec:
  selector:
    app: demo-devops-python
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
  sessionAffinity: None
