parameters:
- name: workingDirectory
- name: buildImage

jobs:
  - job: BuildAndTest
    displayName: 'Build and Test Python App'
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: ${{ parameters.buildImage }}
    steps:
      - checkout: self
        fetchDepth: 0
      - template: ../steps/python/pythonBuild.yml
        parameters:
          workingDirectory: ${{ parameters.workingDirectory }}
      - template: ../steps/test/testPython.yml
        parameters:
          workingDirectory: ${{ parameters.workingDirectory }}